name: Update Number

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight (UTC)

jobs:
  update-number:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run update_number.py
        run: python3 .github/workflows/update_number.py
